import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  RefreshCw,
  Users,
  Plus,
  Link2,
  Check,
  Trash2,
  MessageSquare,
  ChevronDown,
  ChevronRight,
  ListChecks,
  Save,
  Pencil,
  X,
} from 'lucide-react';
import { BriefingSectionProps, MeetingTopic } from '../../../types';
import { useMeetingsContext } from '../../../context/MeetingsContext';
import { useDataContext } from '../../../context/DataContext';
import { useTeamTasksContext } from '../../../context/TeamTasksContext';
import { generateMeetingSnapshots } from '../../../utils/meeting-snapshots';
import { MemberSnapshotCard } from './MemberSnapshotCard';

export const BriefingSection: React.FC<BriefingSectionProps> = ({ meetingId }) => {
  const {
    meetings,
    meetingSnapshots,
    meetingTopics,
    saveMeetingSnapshots,
    saveMeetingTopic,
    deleteMeetingTopic,
    resolveMeetingTopic,
  } = useMeetingsContext();
  const { teamMembers } = useDataContext();
  const { teamTasks, subtasks, timelineEvents } = useTeamTasksContext();

  const [newTitle, setNewTitle] = useState('');
  const [newDescription, setNewDescription] = useState('');
  const [newTaskId, setNewTaskId] = useState('');
  const [showLinkPanel, setShowLinkPanel] = useState(false);
  const [showResolvedTopics, setShowResolvedTopics] = useState(false);
  const autoGeneratedRef = useRef(false);
  const descRef = useRef<HTMLTextAreaElement>(null);

  const autoResizeDesc = useCallback(() => {
    const el = descRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 100) + 'px';
  }, []);

  useEffect(autoResizeDesc, [newDescription, autoResizeDesc]);

  const snapshots = meetingSnapshots.filter(s => s.meeting_id === meetingId);
  const hasSnapshots = snapshots.length > 0;

  // Auto-generate snapshots on first visit if none exist
  useEffect(() => {
    if (autoGeneratedRef.current || hasSnapshots || teamMembers.length === 0) return;
    autoGeneratedRef.current = true;
    const newSnapshots = generateMeetingSnapshots(
      meetingId,
      teamMembers,
      teamTasks,
      subtasks,
      timelineEvents,
      meetings,
    );
    if (newSnapshots.length > 0) {
      saveMeetingSnapshots(newSnapshots);
    }
  }, [
    hasSnapshots,
    teamMembers,
    meetingId,
    teamTasks,
    subtasks,
    timelineEvents,
    meetings,
    saveMeetingSnapshots,
  ]);

  // All topics for this meeting
  const allTopics = meetingTopics.filter(t => t.meeting_id === meetingId);
  const unresolvedTopics = allTopics.filter(t => !t.resolved);
  const resolvedTopics = allTopics.filter(t => t.resolved);
  const floatingTopics = meetingTopics.filter(t => t.meeting_id === null && !t.resolved);

  // Active team tasks for the dropdown
  const activeTeamTasks = teamTasks.filter(t => t.status !== 'done');

  // Task name lookup
  const taskNameMap = new Map(
    teamTasks.map(t => [t.id, t.jira_ref ? `${t.jira_ref} - ${t.title}` : t.title]),
  );

  const handleGenerate = async () => {
    const newSnapshots = generateMeetingSnapshots(
      meetingId,
      teamMembers,
      teamTasks,
      subtasks,
      timelineEvents,
      meetings,
    );
    await saveMeetingSnapshots(newSnapshots);
  };

  const handleAddTopic = async () => {
    if (!newTitle.trim()) return;
    await saveMeetingTopic({
      meeting_id: meetingId,
      team_task_id: newTaskId || null,
      title: newTitle.trim(),
      description: newDescription.trim(),
      resolved: false,
      resolved_at: null,
      leader_response: '',
    });
    setNewTitle('');
    setNewDescription('');
    setNewTaskId('');
  };

  const handleLinkFloating = async (topicId: string) => {
    const topic = meetingTopics.find(t => t.id === topicId);
    if (topic) {
      await saveMeetingTopic({ ...topic, meeting_id: meetingId, id: topic.id });
    }
  };

  const handleSaveTopicResponse = async (topicId: string, response: string) => {
    const topic = meetingTopics.find(t => t.id === topicId);
    if (topic) {
      await saveMeetingTopic({
        ...topic,
        leader_response: response.trim(),
        id: topic.id,
      });
    }
  };

  const handleSaveTopicEdit = async (
    topicId: string,
    title: string,
    description: string,
  ) => {
    const topic = meetingTopics.find(t => t.id === topicId);
    if (topic) {
      await saveMeetingTopic({
        ...topic,
        title: title.trim(),
        description: description.trim(),
        id: topic.id,
      });
    }
  };

  return (
    <div className="space-y-6">
      {/* Snapshot header */}
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium text-gray-400 flex items-center gap-2">
          <Users size={16} />
          Estado del Equipo
        </h3>
        <button
          onClick={handleGenerate}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          <RefreshCw size={14} />
          {hasSnapshots ? 'Regenerar' : 'Generar'}
        </button>
      </div>

      {/* Snapshots per member */}
      {hasSnapshots ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {snapshots.map(snapshot => (
            <MemberSnapshotCard key={snapshot.id} snapshot={snapshot} meetingId={meetingId} />
          ))}
        </div>
      ) : (
        <div className="text-center py-8 text-gray-500">
          <Users size={32} className="mx-auto mb-2 opacity-50" />
          <p className="text-sm">No se ha generado el estado del equipo</p>
          <p className="text-xs mt-1">
            Haz click en &quot;Generar&quot; para capturar el estado actual
          </p>
        </div>
      )}

      {/* Separator */}
      <div className="border-t border-gray-800" />

      {/* Topics section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-medium text-gray-400 flex items-center gap-2">
            <MessageSquare size={16} />
            Temas ({unresolvedTopics.length})
          </h3>
          {floatingTopics.length > 0 && (
            <button
              onClick={() => setShowLinkPanel(!showLinkPanel)}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-gray-700 text-gray-300 rounded-lg hover:bg-gray-600 transition-colors"
            >
              <Link2 size={14} />
              Vincular ({floatingTopics.length})
            </button>
          )}
        </div>

        {/* Link floating topics panel */}
        {showLinkPanel && floatingTopics.length > 0 && (
          <div className="bg-gray-800/50 rounded-lg p-3 border border-gray-700">
            <p className="text-xs text-gray-400 mb-2">Temas pendientes sin reunión:</p>
            <div className="space-y-1">
              {floatingTopics.map(topic => (
                <div key={topic.id} className="flex items-center justify-between py-1.5">
                  <span className="text-sm truncate">{topic.title}</span>
                  <button
                    onClick={() => handleLinkFloating(topic.id)}
                    className="text-xs text-blue-400 hover:text-blue-300 flex-shrink-0 ml-2"
                  >
                    Vincular
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Add new topic form */}
        <div className="flex flex-col gap-2">
          <div className="flex gap-2">
            <input
              type="text"
              value={newTitle}
              onChange={e => setNewTitle(e.target.value)}
              placeholder="Nuevo tema..."
              className="flex-1 border border-gray-700 rounded-lg px-3 py-2 text-sm"
              onKeyDown={e => e.key === 'Enter' && !e.shiftKey && handleAddTopic()}
            />
            <button
              onClick={handleAddTopic}
              disabled={!newTitle.trim()}
              className="px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Plus size={18} />
            </button>
          </div>
          <div className="flex gap-2">
            <textarea
              ref={descRef}
              value={newDescription}
              onChange={e => setNewDescription(e.target.value)}
              placeholder="Descripción (opcional)"
              className="flex-1 border border-gray-700 rounded-lg px-3 py-2 text-sm resize-none overflow-y-auto max-h-[100px] min-h-[38px]"
              rows={1}
              onKeyDown={e => {
                if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
                  e.preventDefault();
                  handleAddTopic();
                }
              }}
            />
            <select
              value={newTaskId}
              onChange={e => setNewTaskId(e.target.value)}
              className="border border-gray-700 rounded-lg px-3 py-2 text-sm bg-gray-800 max-w-[200px] self-start"
            >
              <option value="">Sin tarea vinculada</option>
              {activeTeamTasks.map(t => (
                <option key={t.id} value={t.id}>
                  {t.jira_ref ? `${t.jira_ref} - ` : ''}
                  {t.title}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* All unresolved topics */}
        {unresolvedTopics.length > 0 ? (
          <ul className="space-y-2">
            {unresolvedTopics.map(topic => (
              <TopicItem
                key={topic.id}
                topic={topic}
                taskName={topic.team_task_id ? (taskNameMap.get(topic.team_task_id) ?? null) : null}
                onResolve={resolveMeetingTopic}
                onDelete={deleteMeetingTopic}
                onSaveResponse={handleSaveTopicResponse}
                onSaveEdit={handleSaveTopicEdit}
              />
            ))}
          </ul>
        ) : (
          <p className="text-sm text-gray-500 italic text-center py-3">Sin temas pendientes</p>
        )}

        {/* Resolved topics */}
        {resolvedTopics.length > 0 && (
          <div>
            <button
              onClick={() => setShowResolvedTopics(!showResolvedTopics)}
              className="text-xs text-gray-500 mb-2 flex items-center gap-1 hover:text-gray-400"
            >
              {showResolvedTopics ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
              Resueltos ({resolvedTopics.length})
            </button>
            {showResolvedTopics && (
              <ul className="space-y-1">
                {resolvedTopics.map(topic => (
                  <li
                    key={topic.id}
                    className="flex items-center justify-between py-1.5 px-3 bg-gray-800/50 rounded-lg opacity-60"
                  >
                    <span className="text-sm line-through">{topic.title}</span>
                    <button
                      onClick={() => deleteMeetingTopic(topic.id)}
                      className="p-1 text-gray-500 hover:text-red-400"
                    >
                      <Trash2 size={14} />
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

// Sub-component for a topic item with edit mode, task badge, and comments
function TopicItem({
  topic,
  taskName,
  onResolve,
  onDelete,
  onSaveResponse,
  onSaveEdit,
}: {
  topic: MeetingTopic;
  taskName: string | null;
  onResolve: (id: string) => void;
  onDelete: (id: string) => void;
  onSaveResponse: (id: string, response: string) => void;
  onSaveEdit: (id: string, title: string, description: string) => void;
}) {
  const [response, setResponse] = useState(topic.leader_response ?? '');
  const [editing, setEditing] = useState(false);
  const [editTitle, setEditTitle] = useState(topic.title);
  const [editDescription, setEditDescription] = useState(topic.description);
  const responseRef = useRef<HTMLTextAreaElement>(null);
  const editDescRef = useRef<HTMLTextAreaElement>(null);

  const autoResizeResponse = useCallback(() => {
    const el = responseRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 80) + 'px';
  }, []);

  const autoResizeEditDesc = useCallback(() => {
    const el = editDescRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 80) + 'px';
  }, []);

  useEffect(autoResizeResponse, [response, autoResizeResponse]);
  useEffect(autoResizeEditDesc, [editDescription, autoResizeEditDesc]);

  const responseChanged = response.trim() !== (topic.leader_response ?? '');

  const handleSaveResponse = () => {
    if (!responseChanged) return;
    onSaveResponse(topic.id, response);
  };

  const handleResponseKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      handleSaveResponse();
    }
  };

  const handleStartEdit = () => {
    setEditTitle(topic.title);
    setEditDescription(topic.description);
    setEditing(true);
  };

  const handleCancelEdit = () => {
    setEditing(false);
  };

  const handleConfirmEdit = () => {
    if (!editTitle.trim()) return;
    onSaveEdit(topic.id, editTitle, editDescription);
    setEditing(false);
  };

  const handleEditKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      handleConfirmEdit();
    }
    if (e.key === 'Escape') {
      handleCancelEdit();
    }
  };

  return (
    <li className="bg-gray-800 rounded-lg p-3 border border-gray-700">
      <div className="flex items-start gap-3">
        <div className="flex-1 min-w-0">
          {editing ? (
            <div className="space-y-2">
              <input
                type="text"
                value={editTitle}
                onChange={e => setEditTitle(e.target.value)}
                onKeyDown={handleEditKeyDown}
                className="w-full border border-gray-600 rounded px-2 py-1 text-sm bg-gray-800/50 focus:border-blue-500 focus:outline-none"
                autoFocus
              />
              <textarea
                ref={editDescRef}
                value={editDescription}
                onChange={e => setEditDescription(e.target.value)}
                onKeyDown={handleEditKeyDown}
                placeholder="Descripción (opcional)"
                rows={1}
                className="w-full border border-gray-600 rounded px-2 py-1 text-xs bg-gray-800/50 resize-none overflow-y-auto max-h-[80px] min-h-[28px] focus:border-blue-500 focus:outline-none"
              />
              <div className="flex gap-1.5">
                <button
                  onClick={handleConfirmEdit}
                  disabled={!editTitle.trim()}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50"
                >
                  <Save size={12} />
                  Guardar
                </button>
                <button
                  onClick={handleCancelEdit}
                  className="flex items-center gap-1 px-2 py-1 text-xs text-gray-400 hover:text-gray-200 rounded hover:bg-gray-700"
                >
                  <X size={12} />
                  Cancelar
                </button>
              </div>
            </div>
          ) : (
            <>
              <p className="text-sm font-medium">{topic.title}</p>
              {topic.description && (
                <p className="text-xs text-gray-400 mt-1">{topic.description}</p>
              )}
              {taskName && (
                <div className="mt-1.5 flex items-center gap-1">
                  <ListChecks size={11} className="text-blue-400 flex-shrink-0" />
                  <span className="text-[11px] text-blue-400 truncate">{taskName}</span>
                </div>
              )}
            </>
          )}
        </div>
        {!editing && (
          <div className="flex items-center gap-1 flex-shrink-0">
            <button
              onClick={handleStartEdit}
              className="p-1.5 text-gray-400 hover:bg-gray-700 hover:text-gray-200 rounded"
              title="Editar"
            >
              <Pencil size={14} />
            </button>
            <button
              onClick={() => onResolve(topic.id)}
              className="p-1.5 text-green-400 hover:bg-green-400/10 rounded"
              title="Marcar como resuelto"
            >
              <Check size={16} />
            </button>
            <button
              onClick={() => onDelete(topic.id)}
              className="p-1.5 text-red-400 hover:bg-red-400/10 rounded"
              title="Eliminar"
            >
              <Trash2 size={16} />
            </button>
          </div>
        )}
      </div>
      {!editing && (
        <div className="mt-2">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[10px] text-purple-400">Comentarios</span>
            {responseChanged && (
              <button
                onClick={handleSaveResponse}
                className="flex items-center gap-1 text-[10px] text-purple-400 hover:text-purple-300 transition-colors"
                title="Guardar (Ctrl+Enter)"
              >
                <Save size={10} />
                Guardar
              </button>
            )}
          </div>
          <textarea
            ref={responseRef}
            value={response}
            onChange={e => setResponse(e.target.value)}
            onKeyDown={handleResponseKeyDown}
            placeholder="Sin comentarios..."
            rows={1}
            className="w-full border border-gray-600 rounded px-2 py-1 text-xs bg-gray-800/50 resize-none overflow-y-auto max-h-[80px] focus:border-purple-500 focus:outline-none transition-colors"
          />
        </div>
      )}
    </li>
  );
}
